/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPaymentSettingsRouteImport } from './routes/admin/payment-settings'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminHomepageSettingsRouteImport } from './routes/admin/homepage-settings'
import { Route as AdminIdRouteImport } from './routes/admin/$id'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentSettingsRoute = AdminPaymentSettingsRouteImport.update({
  id: '/admin/payment-settings',
  path: '/admin/payment-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageSettingsRoute = AdminHomepageSettingsRouteImport.update({
  id: '/admin/homepage-settings',
  path: '/admin/homepage-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/status': typeof StatusRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/homepage-settings': typeof AdminHomepageSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/status': typeof StatusRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/homepage-settings': typeof AdminHomepageSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/status': typeof StatusRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/homepage-settings': typeof AdminHomepageSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/status'
    | '/admin/$id'
    | '/admin/homepage-settings'
    | '/admin/login'
    | '/admin/payment-settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/status'
    | '/admin/$id'
    | '/admin/homepage-settings'
    | '/admin/login'
    | '/admin/payment-settings'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/status'
    | '/admin/$id'
    | '/admin/homepage-settings'
    | '/admin/login'
    | '/admin/payment-settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  StatusRoute: typeof StatusRoute
  AdminIdRoute: typeof AdminIdRoute
  AdminHomepageSettingsRoute: typeof AdminHomepageSettingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentSettingsRoute: typeof AdminPaymentSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payment-settings': {
      id: '/admin/payment-settings'
      path: '/admin/payment-settings'
      fullPath: '/admin/payment-settings'
      preLoaderRoute: typeof AdminPaymentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage-settings': {
      id: '/admin/homepage-settings'
      path: '/admin/homepage-settings'
      fullPath: '/admin/homepage-settings'
      preLoaderRoute: typeof AdminHomepageSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  StatusRoute: StatusRoute,
  AdminIdRoute: AdminIdRoute,
  AdminHomepageSettingsRoute: AdminHomepageSettingsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentSettingsRoute: AdminPaymentSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
